language: generic 
sudo: required
services:
  - docker

before_install: 
  - docker build -t rakshak1344/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true rakshak1344/react-test npm test


after_success: 
  - docker build -t rakshak1344/multi-client ./client
  - docker build -t rakshak1344/multi-nginx ./nginx
  - docker build -t rakshak1344/multi-server ./server
  - docker build -t rakshak1344/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push rakshak1344/multi-client
  - docker push rakshak1344/multi-nginx
  - docker push rakshak1344/multi-server
  - docker push rakshak1344/multi-worker